version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LLAMA_API_URL=${LLAMA_API_URL:-}
      - LLAMA_MODEL=${LLAMA_MODEL:-}
      - LLAMA_API_KEY=${LLAMA_API_KEY:-}
      - CEREBRAS_API_URL=${CEREBRAS_API_URL:-}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY:-}
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://backend:8000
    depends_on:
      - backend
