import React from 'react';

function AIInsightCard() {
  return (
    <div className="bg-white shadow-md rounded-lg p-6 hover:shadow-xl transition-shadow">
      <h3 className="text-lg font-semibold text-gray-800">SIP Recommendation</h3>
      <p className="text-gray-600 mt-2">
        Based on your portfolio, increasing your monthly SIP by ₹5,000 could help you reach your goal by 2035.
      </p>
      <p className="text-gray-500 mt-1 text-sm">Generated by AI</p>
      <button className="mt-4 bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">
        View Details
      </button>
    </div>
  );
}

export default AIInsightCard;
